### ISSUE TITLE
confint()| Error: New columns must be compatible with `.data`.

### ISSUE THREAD

**Issue by Dallak** [gavinsimpson/schoenberg#9]
Thanks for the great package, Gavins!

I am trying to extract the predictions of the following model but I keep getting this error.

```
Error: New columns must be compatible with `.data`.
x New column has 1200 rows.
i `.data` has 1000 rows.
```

The model structure is:

```
model = gam(pF0 ~      x1x2 + 
                                      s(time) + 
                                      s(time, word, bs = "re")+
                                      s(time, subject, bs = "re")+ 
                                      s(time, by =x1x2 , bs = 'cr', k = 10),
                                       data = dat, method = "ML")
```

I just want to extract the predictions of the smooth with interaction (x1x2), but when using the following code:

```
confint(model, parm="x1x2", type="confidence", partial_match = T)
```
I get the error massage, but when replacing `x1x2` with `subject` inside `confint()`, for instance, it extracts the predictions of the subjects, not including that of the interaction. any advice?

Thank you in advance!

**Comment by gavinsimpson** [comment]
I don't think `confint()` is the right tool for this. If you want to evaluate the `s(time, by = x1x2)` smooth (if that's what you mean by "predictions of the smooth"), I would use `smooths(model)` to list the names of the smooths in your GAM and then do `smooth_estimates(model, smooth = smooths_wanted)) %>% add_confint()`, replacing `smooths_wanted` with the character vector of smooth labels/names for the factor by smooths. You could do:

```r
s_nms <- smooths(model)
s_nms
sm <- smooth_estimates(model, smooth = s_nms[c(3,4,5)]) %>%
  add_confint()
```

assuming that the 3rd, 4th, and 5th elements of `s_nms` are the factor by smooths you want. If not, just change the indices in the square brackets.

If you want actual predictions from the mode, I would use `fitted_values()`.

`confint()` is one of those old functions in {gratia} that has been a bit overlooked. I'll have to see why it's not working in this case of a factor by term. I'm not exactly sure what the issue is, although as the `x1x2` thing you are matching on is in the `by` part of the model that may be where the problem lies.

Why do you have *linear* random effects for `time` when you are otherwise estimating smooths of `time`?

**Comment by gavinsimpson** [comment]
Oh, you shouldn't be using {schoenberg} - I didn't notice that this was the schoenberg repo. That package is deprecated in favour of my {gratia} package as someone already released a package called schoenberg to CRAN. All the code I mentioned above is using the functionality from {gratia}

**Comment by gavinsimpson** [comment]
{gratia} is on CRAN and the repo for the package is https://github.com/gavinsimpson/gratia

**Comment by Dallak** [comment]
Thank you, Gavins, for your quick reply!
Both ways you presented worked perfectly.

Do you recommend removing `time`? I am using it this way as most of the literature in my field use it this way? any advice?

{gratia} is already installed and I enjoy every bit of it.
